### ISSUE TITLE
Undefined globPattern warning during npm install

### ISSUE THREAD

**Issue by ninjatronic** [SquireLabs/ember-datepicker#26]
Installing for the first time into a project...

![screen shot 2015-01-26 at 14 14 53](https://cloud.githubusercontent.com/assets/4722391/5900909/bdeefb7a-a565-11e4-84f7-dfd15cd942f0.png)

```
ripley:vapr pete$ ember install:addon ember-cli-datepicker
version: 0.1.9
Installed packages for tooling via npm.
installing
The globPattern "undefined" did not match any files, so no file updates will be made.
Installing browser packages via Bower...
  not-cached git://github.com/dbushell/Pikaday.git#*
  resolved git://github.com/dbushell/Pikaday.git#1.3.1
Installed browser packages via Bower.
Installing browser packages via Bower...
  not-cached git://github.com/moment/moment.git#*
  resolved git://github.com/moment/moment.git#2.9.0
Installed browser packages via Bower.
Installed addon package.
```

**Comment by trabus** [comment]
Sorry about this, it was [happening with any blueprint that didn't have files in it](https://github.com/ember-cli/ember-cli/issues/3142). 
The good news is, it was a benign warning, and didn't affect the install process. And the even better news is that it's gone as of ember-cli 0.1.13. 

Please feel free to close this issue.

**Comment by ninjatronic** [comment]
Thanks :)
